version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 11.a, < 12"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: "@types/node"
    versions:
    - ">= 14.0.a, < 14.1"
  - dependency-name: "@types/node"
    versions:
    - ">= 14.6.a, < 14.7"
  - dependency-name: npm
    versions:
    - 7.5.2
    - 7.5.4
    - 7.6.0
    - 7.6.1
    - 7.6.3
    - 7.7.5
    - 7.7.6
    - 7.8.0
    - 7.9.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.3
